#!/bin/bash
# install-language.sh -- Universal language SDK installer for claudebox containers
# Reads /tmp/claudebox-provider.json to determine what to install.
# Runs as root throughout. SDK installs execute as node user (via su). extra_commands run as root with node env sourced.
#
# JSON structure:
#   {name, apt_deps[], install_commands[], env{}, extra_commands[]}
#
# For dotnet: delegates to install-dotnet.sh which scans .csproj files
set -euo pipefail

PROVIDER_JSON="/tmp/claudebox-provider.json"

if [[ ! -f "$PROVIDER_JSON" ]]; then
    echo "Warning: No provider config found at ${PROVIDER_JSON}. Skipping language setup."
    exit 0
fi

LANG_NAME=$(jq -r '.name' "$PROVIDER_JSON")
echo "Setting up language: ${LANG_NAME}"

# --- Refresh apt package lists (always, so extra_commands and modules can install packages) ---
apt-get update -qq

# --- Install apt dependencies (as root) ---
APT_DEPS=$(jq -r '.apt_deps[]?' "$PROVIDER_JSON")
if [[ -n "$APT_DEPS" ]]; then
    echo "Installing apt packages..."
    echo "$APT_DEPS" | xargs apt-get install -y --no-install-recommends -qq
    echo "Apt packages installed."
fi

# --- Set environment variables ---
# Write env vars to a profile script so they're available in shells
ENV_FILE="/home/node/.env.sh"
echo "# Generated by install-language.sh" > "$ENV_FILE"
jq -r '.env // {} | to_entries[] | "export \(.key)=\"\(.value)\""' "$PROVIDER_JSON" >> "$ENV_FILE"

# Write module env vars to .env.sh
MODULE_ENV=$(jq -r '.module_env // {} | to_entries[] | "export \(.key)=\"\(.value)\""' "$PROVIDER_JSON" 2>/dev/null || true)
if [[ -n "$MODULE_ENV" ]]; then
    echo "$MODULE_ENV" >> /home/node/.env.sh
fi

chown node:node "$ENV_FILE"

# Source env for current script context
# shellcheck disable=SC1090
source "$ENV_FILE" 2>/dev/null || true

# Ensure .env.sh is sourced by shell profiles
for profile in /home/node/.bashrc /home/node/.zshrc; do
    if [[ -f "$profile" ]]; then
        if ! grep -q '.env.sh' "$profile" 2>/dev/null; then
            echo '[ -f ~/.env.sh ] && source ~/.env.sh' >> "$profile"
        fi
    else
        echo '[ -f ~/.env.sh ] && source ~/.env.sh' > "$profile"
        chown node:node "$profile"
    fi
done

# --- Fix ownership of named volume mounts ---
# Named volumes are created by Docker as root; chown them so the node user can write.
VOL_PATHS=$(jq -r '.volumes // {} | values[]' "$PROVIDER_JSON")
if [[ -n "$VOL_PATHS" ]]; then
    while IFS= read -r vpath; do
        [[ -z "$vpath" ]] && continue
        if [[ -d "$vpath" ]]; then
            echo "Fixing ownership: ${vpath}"
            chown -R node:node "$vpath"
        fi
    done <<< "$VOL_PATHS"
fi

# --- Run install commands (as node user) ---
INSTALL_CMDS=$(jq -r '.install_commands[]?' "$PROVIDER_JSON")
if [[ -n "$INSTALL_CMDS" ]]; then
    echo "Running install commands as node user..."
    while IFS= read -r cmd; do
        [[ -z "$cmd" ]] && continue
        # Special case: if command is a script name (no path separator), look in /usr/local/bin
        if [[ "$cmd" == *"/"* ]]; then
            su -s /bin/bash -c "source ~/.env.sh 2>/dev/null; $cmd" node
        else
            # It's a script name like "install-dotnet.sh"
            su -s /bin/bash -c "source ~/.env.sh 2>/dev/null; /usr/local/bin/$cmd" node
        fi
    done <<< "$INSTALL_CMDS"
fi

# --- Inject NuGet.Config for dotnet containers with seed cache ---
# Runs only when the read-only bind mount is present at /home/node/.nuget-cache-seed (ref: DL-005).
# Writes to user-scope path (/home/node/.nuget/NuGet/NuGet.Config); dotnet CLI
# reads this location without extra flags (ref: DL-003).
# Machine-wide /etc/NuGet/NuGet.Config was not used: that directory is absent
# in the base image and requires separate creation (ref: DL-003).
# Backs up any existing file to NuGet.Config.bak before overwriting.
if [[ "$LANG_NAME" == "dotnet" ]] && [[ -d "/home/node/.nuget-cache-seed" ]]; then
    NUGET_CONFIG_DIR="/home/node/.nuget/NuGet"
    NUGET_CONFIG_FILE="${NUGET_CONFIG_DIR}/NuGet.Config"
    mkdir -p "$NUGET_CONFIG_DIR"
    if [[ -f "$NUGET_CONFIG_FILE" ]]; then
        echo "Warning: Existing NuGet.Config backed up to NuGet.Config.bak" >&2
        cp "$NUGET_CONFIG_FILE" "${NUGET_CONFIG_DIR}/NuGet.Config.bak"
    fi
    # nuget.org retained alongside local-seed so managed packages not in the
    # seed cache are still resolvable via the allowlisted domain.
    cat > "$NUGET_CONFIG_FILE" <<'NUGET_CONFIG'
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="local-seed" value="/home/node/.nuget-cache-seed" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
NUGET_CONFIG
    chown -R node:node "$NUGET_CONFIG_DIR"
    echo "NuGet.Config injected with local-seed source at /home/node/.nuget-cache-seed"
fi

# --- Run extra commands (as root, with node env sourced) ---
EXTRA_CMDS=$(jq -r '.extra_commands[]?' "$PROVIDER_JSON")
if [[ -n "$EXTRA_CMDS" ]]; then
    echo "Running extra commands..."
    while IFS= read -r cmd; do
        [[ -z "$cmd" ]] && continue
        bash -c "source /home/node/.env.sh 2>/dev/null; $cmd"
    done <<< "$EXTRA_CMDS"
fi

echo "Language setup complete: ${LANG_NAME}"
